python run.py --agt 10 --usr 1 --max_turn 40 \
	      --movie_kb_path /media/bhargavi/Windows1/Users/bharg/Desktop/Courses/Deep_RL/Project/TC-Bot/src/deep_dialog/data/movie_kb.1k.p \
	      --dqn_hidden_size 80 \
	      --experience_replay_pool_size 1000 \
	      --episodes 500 \
	      --simulation_epoch_size 100 \
	      --write_model_dir /media/bhargavi/Windows1/Users/bharg/Desktop/Courses/Deep_RL/Project/TC-Bot/src/deep_dialog/checkpoints/rl_agent/ \
	      --run_mode 3 \
	      --act_level 0 \
	      --slot_err_prob 0.00 \
	      --intent_err_prob 0.00 \
	      --batch_size 16 \
	      --goal_file_path /media/bhargavi/Windows1/Users/bharg/Desktop/Courses/Deep_RL/Project/TC-Bot/src/deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p \
	      --warm_start 1 \
	      --warm_start_epochs 120 \
