python run.py --agt 15 --usr 1 --max_turn 40 \
          --movie_kb_path ./deep_dialog/data/movie_kb.1k.p \
          --dqn_hidden_size 80 \
          --experience_replay_pool_size 1000 \
          --episodes 4000 \
          --simulation_epoch_size 50 \
          --write_model_dir ./deep_dialog/checkpoints/sa2c/ \
          --run_mode 10 \
          --act_level 0 \
          --slot_err_prob 0.00 \
          --intent_err_prob 0.00 \
          --batch_size 16 \
          --goal_file_path ./deep_dialog/data/user_goals_first_turn_template.part.movie.v1.p \
          --warm_start 1 \
          --warm_start_epochs 1 \
          --cmd_input_mode 0 \
          --save_check_point 500 \
          --is_a2c \
          --lrate 0.001 \
          --critw 2.0 \
          --n 10 \
          --gamma 0.9 \
          --a2c_hidden_size 50 \
